# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DisasterAlertApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AWSMobileClient'
  pod 'AWSSNS'

  # Pods for DisasterAlertApp

  target 'DisasterAlertAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DisasterAlertAppUITests' do
    # Pods for testing
  end

end
