# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'DisasterAlertsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AWSCore'
  pod 'AWSMobileClient'
  pod 'AWSSNS'
  pod 'AWSLambda'           # Lambda 서비스 (필요 시 추가)

  # Pods for DisasterAlertsApp

  target 'DisasterAlertsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DisasterAlertsAppUITests' do
    # Pods for testing
  end

end
